name: Workflow with Data Point Capture

on: [push]

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Create JSON payload
        run: |
          json_payload=$(cat <<EOF
          {
            "event_name": "${{ github.event_name }}",
            "job": "${{ github.job }}",
            "workflow": "${{ github.workflow }}",
            "run_id": "${{ github.run_id }}",
            "run_number": "${{ github.run_number }}",
            "actor": "${{ github.actor }}",
            "repository": "${{ github.repository }}",
            "repository_owner": "${{ github.repository_owner }}",
            "sha": "${{ github.sha }}",
            "ref": "${{ github.ref }}",
            "head_ref": "${{ github.head_ref }}",
            "base_ref": "${{ github.base_ref }}",
            "event_path": "${{ github.event_path }}"
          }
          EOF
          )
          echo "JSON Payload: $json_payload"
          echo "JSON_PAYLOAD=$json_payload" >> $GITHUB_ENV
        shell: /usr/bin/bash -e {0}

      # Example step that uses the payload
      - name: Use JSON payload
        run: |
          echo "Received JSON Payload: $JSON_PAYLOAD"
