name: Workflow with Data Point Capture

on: [push]

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo workflow details
        run: |
          echo "Workflow triggered by event: ${{ github.event_name }}"
          echo "Current job name: ${{ github.job }}"
        shell: /usr/bin/bash -e {0}

