name: Workflow with Data Point Capture

on: [push]

jobs:
  audit-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Create JSON payload
        id: create_payload
        run: |
          json_payload=$(cat <<EOF
          {
            "event_name": "${{ github.event_name }}",
            "job": "${{ github.job }}",
            "workflow": "${{ github.workflow }}",
            "run_id": "${{ github.run_id }}",
            "run_number": "${{ github.run_number }}",
            "actor": "${{ github.actor }}",
            "repository": "${{ github.repository }}",
            "repository_owner": "${{ github.repository_owner }}",
            "sha": "${{ github.sha }}",
            "ref": "${{ github.ref }}",
            "head_ref": "${{ github.head_ref }}",
            "base_ref": "${{ github.base_ref }}",
            "event_path": "${{ github.event_path }}"
          }
          EOF
          )
          echo "JSON Payload: $json_payload"
          echo "::set-output name=json_payload::$json_payload"
        shell: /usr/bin/bash -e {0}

      - name: Sign JSON payload
        run: |
          echo "Signing the payload etc.."
